=== broxus/ever-wallet-browser-extension/src/shared/config/networks_config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "defaultConnectionId": {
        "type": "string"
      },
      "networks": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": { "type": "string" },
            "network": { "type": "string", "enum": ["everscale", "tycho", "venom", "ton", "hamster", "custom"] },
            "name": { "type": "string" },
            "group": { "type": "string"},
            "config": {
              "type": "object",
              "additionalProperties": true
            },
            "sortingOrder": { "type": "integer" },
            "isViewOnOnboarding": { "type": "boolean" },
            "type": { "type": "string", "enum": ["graphql", "jrpc", "proto"] },
            "endpoint": {
              "type": "string"
            },
            "endpoints": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": ["id", "network", "name", "group", "config", "sortingOrder", "type"]
        }
      },
      "defaultBlockhainSettings": {
        "type": "object",
        "properties": {
          "walletDefaultAccountNames": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "separateDeployWalletTypes": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "SafeMultisigWallet",
                "SafeMultisigWallet24h",
                "SetcodeMultisigWallet",
                "SetcodeMultisigWallet24h",
                "BridgeMultisigWallet",
                "SurfWallet",
                "Multisig2",
                "Multisig2_1",
                "WalletV3",
                "HighloadWalletV2",
                "EverWallet",
                "WalletV3R1",
                "WalletV3R2",
                "WalletV4R1",
                "WalletV4R2",
                "WalletV5R1"
              ]
            }
          },
          "unsupportedByLedger": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "SafeMultisigWallet",
                "SafeMultisigWallet24h",
                "SetcodeMultisigWallet",
                "SetcodeMultisigWallet24h",
                "BridgeMultisigWallet",
                "SurfWallet",
                "Multisig2",
                "Multisig2_1",
                "WalletV3",
                "HighloadWalletV2",
                "EverWallet",
                "WalletV3R1",
                "WalletV3R2",
                "WalletV4R1",
                "WalletV4R2",
                "WalletV5R1"
              ]
            }
          }
        },
        "required": ["walletDefaultAccountNames", "separateDeployWalletTypes", "unsupportedByLedger"]
      },
      "blockchains": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "networkName": { "type": "string" },
            "network": { "type": "string", "enum": ["everscale", "tycho", "venom", "ton", "hamster", "custom"] },
            "networkGroup": { "type": "string" },
            "icons": {
              "type": "object",
              "properties": {
                "nativeToken": { "type": "string" },
                "network": { "type": "string" },
                "vector": { "type": "string" }
              },
              "required": ["nativeToken", "network", "vector"]
            },
            "walletDefaultAccountNames": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "availableWalletTypes": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                        "SafeMultisigWallet",
                        "SafeMultisigWallet24h",
                        "SetcodeMultisigWallet",
                        "SetcodeMultisigWallet24h",
                        "BridgeMultisigWallet",
                        "SurfWallet",
                        "Multisig2",
                        "Multisig2_1",
                        "WalletV3",
                        "HighloadWalletV2",
                        "EverWallet",
                        "WalletV3R1",
                        "WalletV3R2",
                        "WalletV4R1",
                        "WalletV4R2",
                        "WalletV5R1"
                      ]
                  },
                  "isDeprecated": { "type": "boolean" }
                },
                "required": ["type"]
              }
            },
            "defaultActiveAssets": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "address": { "type": "string" }
                },
                "required": ["address"]
              }
            },
            "defaultWalletType": {
              "type": "string",
              "enum": [
                "SafeMultisigWallet",
                "SafeMultisigWallet24h",
                "SetcodeMultisigWallet",
                "SetcodeMultisigWallet24h",
                "BridgeMultisigWallet",
                "SurfWallet",
                "Multisig2",
                "Multisig2_1",
                "WalletV3",
                "HighloadWalletV2",
                "EverWallet",
                "WalletV3R1",
                "WalletV3R2",
                "WalletV4R1",
                "WalletV4R2",
                "WalletV5R1"
              ]
            },
            "nativeTokenAddress": {
              "type": "string"
            },
            "seedPhraseWordsCount": {
              "type": "array",
              "items": {
                "type": "integer",
                "enum": [12, 24]
              },
              "minItems": 1,
              "maxItems": 2
            },
            "currencyApiBaseUrl": {
              "type": "string"
            },
            "tokenApiUrl": {
              "type": "object",
              "properties": {
                "balances": { "type": "string" }
              },
              "additionalProperties": false
            }
          },
          "required": [
            "networkName",
            "network",
            "networkGroup",
            "icons",
            "availableWalletTypes",
            "defaultWalletType",
            "nativeTokenAddress",
            "seedPhraseWordsCount",
            "currencyApiBaseUrl"
          ]
        }
      }
    },
    "required": [
      "defaultConnectionId",
      "networks",
      "defaultBlockhainSettings",
      "blockchains"
    ]
  }

=== broxus/ever-wallet-browser-extension/src/shared/config/extension_networks_config_prod.json
{
  "$schema": "./networks_config.schema.json",
  "defaultConnectionId": "preset_hmstr_mainnet_proto",
  "networks": [
  {
          "id": "preset_ton_mainnet_jrpc",
          "network": "ton",
          "name": "TON",
          "group": "ton_mainnet",
          "type": "jrpc",
          "endpoint": "https://jrpc-ton.broxus.com",
          "config": {
              "explorerBaseUrl": "https://tonviewer.com",
              "tokensManifestUrl": "https://raw.githubusercontent.com/broxus/ton-assets/refs/heads/ton-prod/manifest.json",
              "symbol": "TON",
              "decimals": 9
          },
          "sortingOrder": 1,
          "isViewOnOnboarding": true
      },
  {
          "id": "preset_hmstr_mainnet_proto",
          "network": "tycho",
          "name": "Hamster Network",
          "group": "hmstr_mainnet",
          "type": "proto",
          "endpoint": "https://rpc.hamster.network",
          "config": {
              "explorerBaseUrl": "https://hamsterscan.io",
              "tokensManifestUrl": "https://raw.githubusercontent.com/broxus/ton-assets/refs/heads/hmstr/manifest.json",
              "symbol": "HMSTR",
              "decimals": 9
          },
          "sortingOrder": 2,
          "isViewOnOnboarding": true
      },
  {
          "id": "preset_humo_testnet_proto",
          "network": "tycho",
          "name": "Humo",
          "group": "humo_testnet",
          "type": "proto",
          "endpoint": "https://rpc.humonetwork.com",
          "config": {
              "explorerBaseUrl": "https://humoscan.com/",
              "symbol": "HUMO",
              "decimals": 9,
              "tokensManifestUrl": "https://raw.githubusercontent.com/broxus/ton-assets/refs/heads/humo/manifest.json"
          },
          "sortingOrder": 3,
          "isViewOnOnboarding": false
      },
  {
          "id": "preset_tycho_testnet_proto",
          "network": "tycho",
          "name": "Tycho Testnet",
          "group": "tycho_testnet",
          "type": "proto",
          "endpoint": "https://rpc-testnet.tychoprotocol.com/proto",
          "config": {
              "explorerBaseUrl": "https://testnet.tychoprotocol.com",
              "tokensManifestUrl": "https://raw.githubusercontent.com/broxus/ton-assets/refs/heads/tychotestnet/manifest.json",
              "symbol": "TYCHO",
              "decimals": 9
          },
          "sortingOrder": 4,
          "isViewOnOnboarding": true
      },
      {
          "id": "preset_ever_mainnet_proto",
          "network": "everscale",
          "name": "Everscale",
          "group": "mainnet",
          "type": "jrpc",
          "endpoint": "https://jrpc.everwallet.net",
          "config": {
              "symbol": "EVER",
              "explorerBaseUrl": "https://everscan.io",
              "tokensManifestUrl": "https://raw.githubusercontent.com/broxus/ton-assets/master/manifest.json",
              "decimals": 9
          },
          "sortingOrder": 5,
          "isViewOnOnboarding": true
      },
      {
          "id": "preset_ever_mainnet_gql",
          "network": "everscale",
          "name": "Everscale (reserve)",
          "group": "mainnet",
          "type": "graphql",
          "endpoints": ["https://mainnet.evercloud.dev/89a3b8f46a484f2ea3bdd364ddaee3a3/graphql"],
          "config": {
              "symbol": "EVER",
              "explorerBaseUrl": "https://everscan.io",
              "tokensManifestUrl": "https://raw.githubusercontent.com/broxus/ton-assets/master/manifest.json",
              "decimals": 9
          },
          "sortingOrder": 6,
          "isViewOnOnboarding": false
      },
      {
          "id": "preset_venom_mainnet_proto",
          "network": "venom",
          "name": "Venom",
          "group": "venom_mainnet",
          "type": "proto",
          "endpoint": "https://jrpc.venom.foundation",
          "config": {
              "symbol": "VENOM",
              "explorerBaseUrl": "https://venomscan.com",
              "tokensManifestUrl": "https://cdn.venom.foundation/assets/mainnet/manifest.json",
              "decimals": 9
          },
          "sortingOrder": 7,
          "isViewOnOnboarding": true
      },
  {
          "id": "preset_msharia_premain_proto",
          "network": "tycho",
          "name": "M.Sharia",
          "group": "msharia_premain",
          "type": "proto",
          "endpoint": "https://rpc.msharia.io",
          "config": {
              "explorerBaseUrl": "https://mshariascan.io",
              "symbol": "MSHA",
              "decimals": 9,
              "tokensManifestUrl": ""
          },
          "sortingOrder": 8,
          "isViewOnOnboarding": false
      }
  ],
  "defaultBlockhainSettings": {
      "walletDefaultAccountNames": {
          "SafeMultisigWallet": "SafeMultisig",
          "SafeMultisigWallet24h": "SafeMultisig24h",
          "SetcodeMultisigWallet": "SetcodeMultisig",
          "SetcodeMultisigWallet24h": "SetcodeMultisig24h",
          "BridgeMultisigWallet": "BridgeMultisig",
          "SurfWallet": "Surf Wallet",
          "Multisig2": "Legacy Multi-sig",
          "Multisig2_1": "Multi-sig",
          "WalletV3": "WalletV3",
          "HighloadWalletV2": "HighloadWallet",
          "EverWallet": "Default",
          "WalletV3R1": "WalletV3R1",
          "WalletV3R2": "WalletV3R2",
          "WalletV4R1": "WalletV4R1",
          "WalletV4R2": "WalletV4R2",
          "WalletV5R1": "WalletV5R1"
      },
      "unsupportedByLedger": [
          "SetcodeMultisigWallet24h",
          "HighloadWalletV2"
      ],
      "separateDeployWalletTypes": [
          "Multisig2",
          "Multisig2_1",
          "SafeMultisigWallet",
          "SafeMultisigWallet24h",
          "SetcodeMultisigWallet",
          "SetcodeMultisigWallet24h",
          "BridgeMultisigWallet",
          "SurfWallet"
      ]
  },
  "blockchains": [
      {
          "networkName": "TON",
          "network": "ton",
          "networkGroup": "ton_mainnet",
          "icons": {
              "nativeToken": "https://raw.githubusercontent.com/broxus/sparx-networks/master/icons/ton/native_token.svg",
              "network": "https://raw.githubusercontent.com/broxus/sparx-networks/master/icons/ton/network.svg",
              "vector": "https://raw.githubusercontent.com/broxus/sparx-networks/master/icons/ton/vector.svg"
      },
          "walletDefaultAccountNames": {
              "WalletV3": "Legacy"
      },
          "availableWalletTypes": [
              {
                  "type": "EverWallet"
              },
              {
                  "type": "Multisig2_1"
              },
              {
                  "type": "WalletV3R1",
                  "isDeprecated": true
              },
              {
                  "type": "WalletV3R2",
                  "isDeprecated": true
              },
              {
                  "type": "WalletV4R1",
                  "isDeprecated": true
              },
              {
                  "type": "WalletV4R2",
                  "isDeprecated": true
              },
              {
                  "type": "WalletV5R1"
              }
          ],
          "defaultActiveAssets": [
              {
                  "address": "0:09f2e59dec406ab26a5259a45d7ff23ef11f3e5c7c21de0b0d2a1cbe52b76b3d"
              }
          ],
          "defaultWalletType": "WalletV5R1",
          "nativeTokenAddress": "0:9a8da514d575d20234c3fb1395ee9138f5f1ad838abc905dc42c2389b46bd015",
          "seedPhraseWordsCount": [
              12,
              24
          ],
          "currencyApiBaseUrl": "https://tonapi.io/v2"
      },
      {
          "networkName": "Hamster Network",
          "network": "tycho",
          "networkGroup": "hmstr_mainnet",
          "icons": {
              "nativeToken": "https://raw.githubusercontent.com/broxus/sparx-networks/master/icons/hamster/native_token.svg",
              "network": "https://raw.githubusercontent.com/broxus/sparx-networks/master/icons/hamster/network.svg",
              "vector": "https://raw.githubusercontent.com/broxus/sparx-networks/master/icons/hamster/vector.svg"
          },
          "availableWalletTypes": [
              {
                  "type": "EverWallet"
              },
              {
                  "type": "Multisig2_1"
              },
              {
                  "type": "WalletV3R1",
                  "isDeprecated": true
              },
              {
                  "type": "WalletV3R2",
                  "isDeprecated": true
              },
              {
                  "type": "WalletV4R1",
                  "isDeprecated": true
              },
              {
                  "type": "WalletV4R2",
                  "isDeprecated": true
              },
              {
                  "type": "WalletV5R1"
              }
          ],
          "defaultActiveAssets": [
              {
                  "address": "0:fddc005ddffcc9c5cc8e2d684c1338d3fa5548426602b04b2cfd2a1a3504be80"
              }
          ],
          "defaultWalletType": "EverWallet",
          "nativeTokenAddress": "0:39b50cd546326f132e57ce3d6c488d08cb3900dc309a53681b82216993384546",
          "seedPhraseWordsCount": [
              12,
              24
          ],
          "currencyApiBaseUrl": "https://api.hamsterdex.io/v1",
          "tokenApiUrl": {
              "balances": "https://tokens.hamsterscan.io/v1/balances/search"
          }
      },
      {
          "networkName": "Humo",
          "network": "tycho",
          "networkGroup": "humo_testnet",
          "icons": {
              "nativeToken": "https://raw.githubusercontent.com/broxus/sparx-networks/master/icons/humo/native_token.svg",
              "network": "https://raw.githubusercontent.com/broxus/sparx-networks/master/icons/humo/network.svg",
              "vector": "https://raw.githubusercontent.com/broxus/sparx-networks/master/icons/humo/vector.svg"
          },
          "availableWalletTypes": [
